"""Deliverable 4 walkthrough: a scanned/image PDF in, correct citations out.

    python scripts/demo_scanned_pdf.py

The hackathon asks for a recorded walkthrough of "the engine processing a scanned/image
PDF document, generating correct citations". This script IS that walkthrough, in one
command, so nothing has to be typed live.

It runs on Malaysia's Computer Crimes Act 1997 as published by the AGC portal: 12 pages,
572 embedded images, and — the point of the demo — a ZERO-character text layer. It is a
photograph of a statute. Every citation printed at the end therefore had to come through
OCR; there is no text to fall back on.

The four steps it shows:

  1. PROOF the PDF is image-only  — extract text WITHOUT OCR, get 0 characters.
  2. OCR                          — RapidOCR (local, open-source, no API key) reads it.
  3. PARSE                        — the OCR'd text is cut into addressable sections.
  4. CITE                         — each provision is mapped to an RDTII indicator, and the
                                    verbatim snippet is copied from the parsed clause, never
                                    generated by a model.

Pass --url to run it on any other scanned statute.
"""
from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

# Malaysia, Computer Crimes Act 1997 (Act 563), AGC official portal. Image-only scan.
DEFAULT_URL = (
    "https://lom.agc.gov.my/ilims/upload/portal/akta/outputaktap/575_BI/"
    "ACT%20563%20-%20WARTA%20ASAL.pdf"
)
DEFAULT_ISO = "my"
RULE = "=" * 78


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default=DEFAULT_URL, help="Scanned statute PDF (official portal)")
    ap.add_argument("--economy", default=DEFAULT_ISO, help="ISO code of the economy")
    ap.add_argument("--no-llm", action="store_true",
                    help="Skip the LLM lanes (BM25 + template rationale only)")
    args = ap.parse_args()

    os.environ["LEXORA_OCR"] = "1"  # the whole point of this demo

    import fitz

    from lexora.cite.rationale import make_rationale_generator
    from lexora.classify.verifier import make_verifier
    from lexora.collect.crawler import fetch
    from lexora.collect.profile_loader import load_profile
    from lexora.indicators import load_indicators
    from lexora.models.source import SourceType
    from lexora.pipeline import run_pipeline_from_url

    profile = load_profile(REPO / "configs" / "jurisdictions" / f"{args.economy}.yaml")
    indicators = load_indicators(REPO / "configs" / "rdtii_indicators.yaml")
    ua = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
          "(KHTML, like Gecko) Chrome/120 Safari/537.36")

    print(RULE)
    print("STEP 1 - Fetch the document from the official government portal")
    print(RULE)
    print(f"  {args.url}\n")
    res = fetch(args.url, jurisdiction=args.economy.upper(), portal_name="demo",
                source_type=SourceType.primary,
                dest_dir=REPO / "data" / "raw" / args.economy,
                timeout=90, browser_fallback=True, user_agent=ua)
    print(f"  HTTP {res.document.http_status}   {len(res.body):,} bytes")
    print(f"  sha256 {res.document.sha256[:16]}...   cached at {res.document.bytes_path}")

    print(f"\n{RULE}")
    print("STEP 2 - PROVE it is a scanned image, not text")
    print(RULE)
    doc = fitz.open(stream=res.body, filetype="pdf")
    raw_text = "".join(doc[i].get_text() for i in range(doc.page_count))
    images = sum(len(doc[i].get_images()) for i in range(doc.page_count))
    print(f"  pages                      : {doc.page_count}")
    print(f"  embedded images            : {images}")
    print(f"  text extractable WITHOUT OCR: {len(raw_text.strip())} characters")
    doc.close()
    if len(raw_text.strip()) == 0:
        print("\n  -> ZERO characters. This PDF is a photograph of a statute.")
        print("     Nothing below could exist without OCR.")
    else:
        print("\n  -> This PDF has a text layer; the OCR path will not be exercised.")

    print(f"\n{RULE}")
    print("STEP 3 - OCR -> parse -> map  (RapidOCR: local, open-source, no API key)")
    print(RULE)
    use_llm = not args.no_llm
    verifier = make_verifier(use_llm=use_llm, mode="per_clause") if use_llm else None
    rationale = make_rationale_generator(use_llm=use_llm)
    t0 = time.time()
    art = run_pipeline_from_url(
        url=args.url, profile=profile, indicators=indicators, portal_name="demo",
        source_type=SourceType.primary, dest_dir=REPO / "data" / "raw" / args.economy,
        top_k=5, min_score=0.1, verifier=verifier, rationale_gen=rationale,
        llm_workers=8, timeout=90, browser_fallback=True, user_agent=ua,
    )
    wall = time.time() - t0
    print(f"  OCR engine        : {art.ocr_engine or 'rapidocr'}")
    print(f"  scanned           : {art.pdf_is_scanned}")
    print(f"  OCR quality (CER) : {art.ocr_quality_cer}")
    print(f"  characters recovered: {len(art.document_text):,}")
    print(f"  clauses parsed    : {len(art.clauses)}")
    print(f"  wall clock        : {wall:.0f}s")

    print(f"\n{RULE}")
    print("STEP 4 - Citations (verbatim snippet copied from the clause, never generated)")
    print(RULE)
    if not art.citations:
        print("  (no citations)")
        return
    for c in art.citations:
        quote = " ".join(c.quote.split())
        print(f"\n  [{c.indicator_id}]  {c.article_path}   (page {c.page_or_dom_anchor})")
        print(f"     confidence : {c.confidence:.2f}")
        if c.mapping_rationale:
            print(f"     rationale  : {c.mapping_rationale[:150]}")
        print(f"     verbatim   : \"{quote[:200]}\"")
    print(f"\n  {len(art.citations)} citation(s) from a PDF with a 0-character text layer.")
    print(f"  Source: {args.url}")


if __name__ == "__main__":
    main()
